# Bloque 1: Configuración e Ingesta de Datos
Objetivo: Cargar las librerías necesarias y crear el dataset. [Inferencia] Dado que el archivo original de marketing a veces da error de carga por internet, usamos un diccionario controlado para asegurar que tu flujo de trabajo no se detenga.

In [1]:
import pandas as pd # Librería principal para manipulación de tablas
import numpy as np  # Librería para operaciones numéricas y valores nulos
import os           # Librería para gestionar carpetas y rutas del sistema

# 1. CREACIÓN DEL DATASET (SIMULACIÓN DE DATOS REALES)
# Creamos un diccionario con errores comunes: espacios en blanco y valores 'unknown'
data = {
    'age': [30, 33, 35, 30, 59],
    'job': [' management', 'technician ', 'entrepreneur', 'blue-collar', 'unknown'], 
    'education': ['tertiary', 'secondary', 'secondary', 'unknown', 'secondary']
}

# Convertimos el diccionario en un DataFrame de Pandas
df_mkt = pd.DataFrame(data)

# 2. VISUALIZACIÓN INICIAL
# .head(): Nos permite ver el estado "sucio" original de los datos
print("--- Datos de Marketing Originales ---")
display(df_mkt.head())

--- Datos de Marketing Originales ---

   age           job  education
0   30    management   tertiary
1   33   technician   secondary
2   35  entrepreneur  secondary
3   30   blue-collar    unknown
4   59       unknown  secondary

# Bloque 2: Normalización de Texto (Data Wrangling)
Objetivo: Unificar el formato de las palabras. En marketing, " Management" y "management" deben ser lo mismo para que la IA no se confunda.

In [2]:
# 1. LIMPIEZA DE LA COLUMNA 'JOB' (TRABAJO)
# .str.lower(): Convierte todo a minúsculas para evitar duplicidad por mayúsculas
# .str.strip(): Elimina los espacios accidentales al principio o al final de la palabra
df_mkt['job'] = df_mkt['job'].str.lower().str.strip()

# 2. LIMPIEZA DE LA COLUMNA 'EDUCATION' (EDUCACIÓN)
# Aplicamos la misma lógica para mantener la consistencia en todo el dataset
df_mkt['education'] = df_mkt['education'].str.lower().str.strip()

# 3. TRATAMIENTO DE VALORES 'UNKNOWN' (DESCONOCIDOS)
# .replace(): Cambiamos la etiqueta genérica 'unknown' por algo más descriptivo
# Esto ayuda a que el análisis posterior sea más humano y claro
df_mkt['job'] = df_mkt['job'].replace('unknown', 'otro_no_definido')

print("✅ Normalización de texto completada.")
display(df_mkt.head())

✅ Normalización de texto completada.

   age               job  education
0   30        management   tertiary
1   33        technician  secondary
2   35      entrepreneur  secondary
3   30       blue-collar    unknown
4   59  otro_no_definido  secondary

# Bloque 3: Gestión de Rutas y Creación de Carpetas
Objetivo: Asegurar que la carpeta de destino existe. [Inferencia] Este bloque es el "Constructor", evita que el código falle si aún no has creado manualmente las carpetas en Windows.

In [4]:
# 1. DEFINICIÓN DE LA RUTA DE SALIDA (RECTIFICADA)
# Subimos 3 niveles (../../..) para salir de: caso_marketing/ > datos/ > notebooks/
# Y luego entramos en la estructura de datos profesional
ruta_procesados = '../../../data/processed/'

# 2. CREACIÓN AUTOMÁTICA DE CARPETAS
# os.path.exists: Comprueba si la carpeta ya existe en tu disco duro
if not os.path.exists(ruta_procesados):
    # os.makedirs: Crea la ruta completa (data y processed) de un solo golpe
    os.makedirs(ruta_procesados)
    print(f"📁 Carpeta creada con éxito en: {ruta_procesados}")
else:
    print("ℹ️ La carpeta de destino ya existe, procediendo al guardado.")
# Usar ruta_procesados ya definida; no depende de variable inexistente 'raiz'
folder_final = os.path.abspath(ruta_procesados)
file_final = os.path.join(folder_final, 'marketing_limpio.csv')

# 3. Crear la carpeta si no existe
os.makedirs(folder_final, exist_ok=True)

# 4. Guardar el archivo
df_mkt.to_csv(file_final, index=False)

print(f"📍 Carpeta procesados: {folder_final}")
if os.path.exists(file_final):
    print(f"✅ ARCHIVO UBICADO CORRECTAMENTE EN: {file_final}")
else:
    print("❌ Error: No se pudo verificar el guardado.")

ℹ️ La carpeta de destino ya existe, procediendo al guardado.
📍 Carpeta procesados: c:\Users\txema\Documents\IA_Especialista\data\processed
✅ ARCHIVO UBICADO CORRECTAMENTE EN: c:\Users\txema\Documents\IA_Especialista\data\processed\marketing_limpio.csv

# Bloque 4: Exportación y Auditoría Final
Objetivo: Guardar el archivo físico y verificar su integridad en el disco duro.

In [5]:
# 1. DEFINICIÓN DEL NOMBRE DEL ARCHIVO
file_path = os.path.join(ruta_procesados, 'marketing_limpio.csv')

# 2. EXPORTACIÓN A CSV
# index=False: Evita que se guarde la columna de números de fila (0, 1, 2...)
df_mkt.to_csv(file_path, index=False)

# 3. COMPROBACIÓN FÍSICA (SYSTEM CHECK)
if os.path.exists(file_path):
    # Obtenemos el tamaño del archivo para confirmar que contiene datos
    size = os.path.getsize(file_path) / 1024
    print(f"\n✅ TRILOGÍA COMPLETADA: El archivo físico existe.")
    print(f"📊 Nombre: marketing_limpio.csv | Tamaño: {size:.2f} KB")
    # Imprimimos la ruta absoluta para que sepas dónde encontrarlo en tu PC
    print(f"📍 Ubicación Real: {os.path.abspath(file_path)}")
else:
    print("\n❌ ERROR: El archivo no se pudo guardar. Revisa los permisos de escritura.")

✅ TRILOGÍA COMPLETADA: El archivo físico existe.
📊 Nombre: marketing_limpio.csv | Tamaño: 0.15 KB
📍 Ubicación Real: c:\Users\txema\Documents\IA_Especialista\data\processed\marketing_limpio.csv